name: Deploy project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.1
    - name: Install Node JS
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install ${{ github.workspace }}/Code/02 Basics/05 Practice Project (Finished)
    - name: Run tests
      run: npm run test ${{ github.workspace }}/Code/02 Basics/05 Practice Project (Finished)
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.1
    - name: Install Node JS
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install ${{ github.workspace }}/Code/02 Basics/05 Practice Project (Finished)
    - name: build the project
      run: npm run build ${{ github.workspace }}/Code/02 Basics/05 Practice Project (Finished)
    - name: deploy
      run: echo deploying
    
        
  
